config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get 'home/about' => 'home#about'


  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update,:create]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])

  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_to book_path(book)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
		redirect_to book_path(params[:book_id])
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def show
    @books = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to book_path(@book.id), notice: "successfully created book!"
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "successfully updated book!"
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  def ensure_correct_user
    @book = Book.find_by(id:params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:update]

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password]
      )
    if @user.save
      flash[:notice] = "Signed in successfully."
      redirect_to users_pash(user.id)
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "successfully updated user!"
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

   def baria_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<% if book.errors.any? %>
  		<div id="error_explanation">
    		<h2>error: <%= book.errors.count %></h2>
    			<ul>
    				<% book.errors.full_messages.each do |msg| %>
      					<li><%= msg %></li>
    				<% end %>
    			</ul>
  		</div>
  	<% end %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>
	<br>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">


		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books</h2>

			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.id) do %>
							<%= attachment_image_tag @book.user, :profile_image, :size => "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>

						<% if book.favorited_by?(current_user) %>
						<td>
							<%= link_to book_favorites_path(book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" ></i>
							<%= book.favorites.count %>
							<% end %>
						</td>
						<% else %>
						<td>
							<%= link_to book_favorites_path(book), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= book.favorites.count %>
							<% end %>
						</td>
						<% end %>

						<td>
							<%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @books %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
					<tr>
						<td>
							<%= link_to user_path(@user.id) do %>
							<%= attachment_image_tag @book.user, :profile_image, :size => "50x50", format: 'jpeg', fallback: "no_image.jpg" %><br>
							<%= @user.name %>
							<% end %>
						</td>
						<td><%= link_to @book.title, @book %></td>
						<td><%= @book.body %></td>

						<% if @book.favorited_by?(current_user) %>
						<td>
							<%= link_to book_favorites_path(@book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" ></i>
							<%= @book.favorites.count %>
							<% end %>
						</td>
						<% else %>
						<td>
							<%= link_to book_favorites_path(@book), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= @book.favorites.count %>
							<% end %>
						</td>
						<% end %>

						<td>
							<a href="#comments">コメント数:<%= @book.book_comments.count %></a>
						</td>

						<td><% if @book.user == current_user %>
							<%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>
							<% end %></td>

						<td><% if @book.user == current_user %>
							<%= link_to "Destroy",book_path(@book.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
							<% end %></td>

					</tr>
			</table>
			<table class="comment-list">
				<% @book.book_comments.each do |book_comment| %>
				  <tr class="comment">
					<div class="comment-body bb">
						<td>
							<div class="comment-avatar">
								<div class="avatar">
									<%= attachment_image_tag @book.user, :profile_image, :size => "50x50", format: 'jpeg', fallback: "no_image.jpg" %><br>
								</div>
							</div>
							<div class="comment-author clearfix">
								<a href="#" class="link-author"><%= book_comment.user.name %></a>
							</div>
						</td>
						<td>
							<span class="comment-meta"></span>
							<div class="comment-entry"><%= book_comment.comment %></div>
						</td>
						<td>
							<span>
								<% if book_comment.user == current_user %>
								  <%= link_to "Destroy",book_book_comment_path(@book, book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book_comment.id}" %>
								<% end %>
							</span>
						</td>
					</div>
				  </tr>
				<% end %>
			</table>
			<%= form_for [@book, @book_comment] do |f| %>
			  <div class="row">
			  	<%= f.text_area :comment, rows:'5', class: "col-xs-10 comment-form",placeholder: "comment" %>
			  </div>
			    <%= f.submit "送信", class: "btn btn-default btn-sm btn-base-1 pull-left" %>
			<% end %>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0c25928deb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="style.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <p id="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <main>
      <div class="container">
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag @book.user, :profile_image, :size => "100x100", format: 'jpeg', fallback: "no_image.jpg" %><br></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

</table>

<% unless current_user != user %>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<h2>User info</h2>

		<%= form_for(@user) do |f| %>

		<% if @user.errors.any? %>
			<h3><%= @user.errors.count %>error occurrence</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>

		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name, class: "name" %>
		</div>

		<div class="field">
			<%= f.label :image %>
			<%= f.attachment_field :profile_image, class: "user_image" %>
		</div>

		<div class="field">
			<%= f.label :introduction %>
			<%= f.text_area :introduction, class: "introduction" %>
		</div>

		<div class="actions">
			<%= f.submit %>
		</div>

		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>

			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag @book.user, :profile_image, :size => "50x50", format: 'jpeg', fallback: "no_image.jpg" %></td>
						<td><%= user.name%></td>

						<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>

			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to book_path(book.id) do %>
							<%= attachment_image_tag @book.user, :profile_image, :size => "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>

						<% if book.favorited_by?(current_user) %>
						<td>
							<%= link_to book_favorites_path(book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" ></i>
							<%= book.favorites.count %>
							<% end %>
						</td>
						<% else %>
						<td>
							<%= link_to book_favorites_path(book), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= book.favorites.count %>
							<% end %>
						</td>
						<% end %>

						<td>
							<%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %>
						</td>

					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

	</div>
</div>